# Generated by Django 2.1 on 2018-08-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='person',
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ManyToManyField(related_name='addresses', to='api.Person'),
        ),
        migrations.RemoveField(
            model_name='email',
            name='person',
        ),
        migrations.AddField(
            model_name='email',
            name='person',
            field=models.ManyToManyField(related_name='emails', to='api.Person'),
        ),
        migrations.RemoveField(
            model_name='phone',
            name='person',
        ),
        migrations.AddField(
            model_name='phone',
            name='person',
            field=models.ManyToManyField(related_name='phones', to='api.Person'),
        ),
    ]
