# Generated by Django 2.1 on 2018-08-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180825_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='person',
            new_name='persons',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='person',
            new_name='persons',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='person',
            new_name='persons',
        ),
    ]
