# Generated by Django 2.1 on 2018-08-27 23:22

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180827_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='addresses',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='person',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None),
        ),
    ]
